apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: chat-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      tolerations:
        - key: dedicated
          operator: Equal
          value: apps-dev
          effect: NoSchedule
      nodeSelector:
        component: apps-dev
      containers:
      - name: chat-app-backend
        image: ankushgudu/chat-app-backend:latest
        ports:
        - containerPort: 5001
        env:
        - name: NODE_ENV
          value: production
        - name: MONGODB_URI
          value: "mongodb://mongoadmin:secret@mongodb:27017/dbname?authSource=admin"
        - name: JWT_SECRET
          value: /;3h?-KgVSc$aBIy!W!7}-(W+A#O;xwJu:b/>qYwS*v&EXGUzE2r(njr&>]T!;-FY!e20IbXnURQq+2z.Na|7P
        - name: PORT
          value: "5001"
