apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-pod
  namespace: chat-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      tolerations:
        - key: dedicated
          operator: Equal
          value: apps-dev
          effect: NoSchedule
      nodeSelector:
        component: apps-dev
      containers:
      - name: mongodb-pod
        image: mongo:latest
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: mongoadmin
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: secret
        volumeMounts:
        - name: mongo-data
          mountPath: data/mongodb
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: mongodb-pvc
